package com.example.finix.data;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "categories")
public class Category {

    // --- NEW: Client's unique ID. This is the Room Primary Key (auto-generated). ---
    // Maps to the server's 'local_id' column for sync tracking.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "local_id")
    private int localId;

    // --- Server's unique ID. This will be 0 until successfully synced. ---
    @ColumnInfo(name = "id", defaultValue = "0")
    private int id;

    @ColumnInfo(name = "name")
    private String name;

    // 1. Explicit no-arg constructor for Room
    public Category() {
        // Required empty public constructor
    }

    // 2. Constructor for creating a *new* Category (localId auto-generated by Room)
    @Ignore
    public Category(String name) {
        this.name = name;
        this.id = 0; // Server ID is 0 until synced
        // localId is generated automatically upon insertion
    }

    // 3. Constructor for existing data or mapping remote data (IDs are known)
    @Ignore
    public Category(int localId, int id, String name) {
        this.localId = localId;
        this.id = id;
        this.name = name;
    }

    // --- Getters & Setters ---

    // Server ID Getters/Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    // Local ID Getters/Setters (Fixes the original error)
    public int getLocalId() { return localId; }
    public void setLocalId(int localId) { this.localId = localId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
}